// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkvALX6e1aCsL3hvx7BzP1uxT_l6GNn1Y',
    appId: '1:288632780899:android:286e12065eb731dc116056',
    messagingSenderId: '288632780899',
    projectId: 'socialmedia-3fd7c',
    storageBucket: 'socialmedia-3fd7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC36YNGly9QLu9mf8peNADOI33GfPGPaUs',
    appId: '1:288632780899:ios:3b0387de9412007f116056',
    messagingSenderId: '288632780899',
    projectId: 'socialmedia-3fd7c',
    storageBucket: 'socialmedia-3fd7c.firebasestorage.app',
    iosBundleId: 'com.example.socialMdia',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVSjctFb-Acknrri7hNc27rqb5BtKclAY',
    appId: '1:288632780899:web:446f1ec9a3231052116056',
    messagingSenderId: '288632780899',
    projectId: 'socialmedia-3fd7c',
    authDomain: 'socialmedia-3fd7c.firebaseapp.com',
    storageBucket: 'socialmedia-3fd7c.firebasestorage.app',
    measurementId: 'G-JL6M8CD543',
  );

}